version: '3'

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app
    command: bundle exec foreman start
    environment:
      REPP_ENV: production
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/igudhizu
    env_file: .env
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: igudhizu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    expose:
      - '5432'
    volumes:
      - ./tmp/volumes/postgresql:/var/lib/postgresql/data
